Repository Harsh-jot/HacktoberFest-2022, pull requests merged in 2022-10, with the labels that each got.

#6 Add sorting algorithms in java
  Programs/Java/BubbleSort.java
  Programs/Java/InsertionSort.java
  Programs/Java/MergeSort.java
  Programs/Java/QuickSort.java
  Programs/Java/SelectionSort.java
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest

#8 this is reverse string cpp program
  Programs/CPP/reversestring.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest

#10 Added some JAVA Programs
  Programs/Java/Daemon_Table.java
  Programs/Java/Integer_to_Roman.java
  Programs/Java/Length_of_Last_Word.java
  Programs/Java/Lowest_Common_Ancestor.java
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest, approved

#13 Added some C Programs
  Programs/C/Plus_Pattern.c
  Programs/C/Pyramid_Pattern.c
  Programs/C/Spiral_Pattern.c
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest, approved

#12 Added some Python Programs
  Programs/Python/Factorial.py
  Programs/Python/Palindrome.py
  Programs/Python/ReadingMatrix.py
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest

#16 Added some JAVA Programs
  Programs/Java/Calc.java
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest

#17 Added some C++ Programs
  Programs/C/Bubble_Sort.c
  Programs/CPP/Num_to_Char.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest, approved

#18 Added some JAVA Programs
  Programs/Java/Heap_Sort.java
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest, approved

#21 Added some Programs in a new directory of patterns under CPP
  Programs/CPP/Patterns/Pyramid_Pattern.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest, approved

#30 Added a C Program
  Programs/C/Factor_of_Number.c
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest, approved

#24 Print Star pattern in Java
  Programs/Java/Pattern.class
  Programs/Java/Pattern.java
Labels: hacktoberfest-accepted, hacktoberfest2022

#31 Added a C++ Program
  Programs/CPP/Leap_Year.cpp
Labels: hacktoberfest-accepted, hacktoberfest2022, hacktoberfest, approved
